#!/bin/bash

# Password file path
password_file=".passwd"

# Read password securely (avoid storing in script)
if [[ -f "$password_file" ]]; then
  # Read first line of password file (assuming password is on the first line)
  key=$(head -n 1 "$password_file")
  echo $key
else
  echo "Password file not found: $password_file"
  exit 1  # Script exits with error (no password)
fi

# LOG FOR NEW CSIL SYSTEM
timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
output_file="csil_vortex-$timestamp.log"
touch "$output_file"
#echo $key | sudo -S chmod 7777 "$output_file"### | tee -a "$output_file"

echo $key | sudo -S touch "$output_file"

sleep 5
echo "# Installing the CSI VORTEX Theme..." | tee -a "$output_file"

###REMOVE old files to ensure that new files are accepted.
echo $key | sudo -S rm /usr/share/plymouth/themes/default.plymouth
echo $key | sudo -S rm /etc/alternatives/default.plymouth

sleep 5
# adding csil-vortex in the list of aviable themes
echo -n "updating plymouth themes alternatives   ........................   " | tee -a "$output_file"
echo $key | sudo -S update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/csil-000/csil-000.plymouth 100 &>/dev/null
echo $key | sudo -S update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/csil-001/csil-001.plymouth 100 &>/dev/null
echo $key | sudo -S update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/vortex-ubuntu/vortex-ubuntu.plymouth 100 &>/dev/null
if [ $? -gt 0 ]; then
  echo -e "\nan error occurred installing alternative in /usr/share/plymouth/themes/default.plymouth" | tee -a "$output_file"
  exit 1
fi
echo "[done]"

# setting csil-vortex as default plymouth theme;
echo -n "setting CSILinux Vortex as default plymouth theme   .................   " | tee -a "$output_file"
#echo $key | sudo -S update-alternatives --set default.plymouth /usr/share/plymouth/themes/csil-000/csil-000.plymouth  &> /dev/null;
echo $key | sudo -S update-alternatives --set default.plymouth /usr/share/plymouth/themes/csil-001/csil-001.plymouth &>/dev/null;
#echo $key | sudo -S update-alternatives --set default.plymouth /usr/share/plymouth/themes/vortex-ubuntu/vortex-ubuntu.plymouth  &> /dev/null ;
#echo $key | sudo -S update-alternatives --set default.plymouth /usr/share/plymouth/themes/csil-003/csil-003.plymouth;
if [ $? -gt 0 ]; then
  echo -e "\nan error occurred setting alternative in /usr/share/plymouth/themes/default.plymouth" | tee -a "$output_file"
  exit 1
fi
echo "[done]"

#sudo update-alternatives --config default.plymouth

# updating Initial RAM File System
echo -n "updating Initial RAM File System   .............................   " | tee -a "$output_file"
echo $key | sudo -S update-initramfs -u &>/dev/null
if [ $? -gt 0 ]; then
  echo -e "\nan error occurred executing \"update-initramfs -u\"" | tee -a "$output_file"
  exit 1
fi
echo "[done]" | tee -a "$output_file"

echo "CSILinux Vortex is your plymouth theme now :)" | tee -a "$output_file"
#exit 0
